services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data_a:/data
    entrypoint: redis-server --appendonly yes

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: password_manager_database
      POSTGRES_USER: ps_user
      POSTGRES_PASSWORD: ps_password

  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=password_manager_database
      - DB_USER=ps_user
      - DB_PASSWORD=ps_password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  redis_data_a:
